info:
  app:
    name: catalog-search-service
    description: Search in the National Library of Norway catalog

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8080

---
spring:
    profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    