info:
  app:
    name: catalog-search-service
    description: Search in the National Library of Norway catalog

spring:
  application:
    name: catalog-search-service

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8083

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: docker

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      
zipkin:
    collector-hostname: zipkinCollector